# Generated by Django 4.2.7 on 2024-01-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
