# Generated by Django 4.2.7 on 2024-01-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
