# Generated by Django 4.2.7 on 2024-01-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('participant', 'Participant'), ('creator', 'Creator')], default='participant', max_length=20),
        ),
    ]
