# Generated by Django 4.2.7 on 2023-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published'), ('archived', 'Archived')], default='drafted', max_length=20),
        ),
    ]
