# Generated by Django 4.2.7 on 2023-11-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventScheduleItem',
            new_name='EventSessionItem',
        ),
    ]
