# Generated by Django 4.2.7 on 2023-12-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(default='Deneme', max_length=255),
            preserve_default=False,
        ),
    ]
