# Generated by Django 4.2.7 on 2024-01-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
