# Generated by Django 4.2.7 on 2024-01-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='static/event_images/'),
        ),
    ]
