# Generated by Django 4.2.7 on 2024-01-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
